name = "uart_saleae_loopback_spade"

[libraries]
shared_components = { path = "../shared-components" }

[constraints]
auto = true

[verilog]
sources = [
    "../shared-verilog/clk_wiz_0.v",
    "../shared-components/verilog/fifo_v.v",
]

[tooling]
top = "main"
test_module = "test_uart_saleae_loopback"

[simulation]
testbench_dir = "test"
