name = "ft_uart_hex_bridge_spade"
preprocessing = ["python3 ../tools/gen_build_info.py --project ."]

[libraries]
shared_components = { path = "../shared-components" }

[constraints]
auto = true

[verilog]
sources = [
    "verilog/main_wrapper.v",
    "../shared-components/verilog/**/*.v",
]

[tooling]
top = "main"
test_module = "test_ft_uart_hex_bridge"

[simulation]
testbench_dir = "test"
