# Sharp Organizer Card Constraint File for Alchitry Au
# Converted from sharp-organizer-card.acf

# Clock and Reset
set_property PACKAGE_PIN N14 [get_ports io_clk]
set_property IOSTANDARD LVCMOS33 [get_ports io_clk]
create_clock -period 10.000 -name io_clk [get_ports io_clk]

set_property PACKAGE_PIN P6 [get_ports io_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports io_rst_n]

# LEDs
set_property PACKAGE_PIN K13 [get_ports {io_led[0]}]
set_property PACKAGE_PIN K12 [get_ports {io_led[1]}]
set_property PACKAGE_PIN L14 [get_ports {io_led[2]}]
set_property PACKAGE_PIN L13 [get_ports {io_led[3]}]
set_property PACKAGE_PIN M16 [get_ports {io_led[4]}]
set_property PACKAGE_PIN M14 [get_ports {io_led[5]}]
set_property PACKAGE_PIN M12 [get_ports {io_led[6]}]
set_property PACKAGE_PIN N16 [get_ports {io_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[*]}]

# USB UART
set_property PACKAGE_PIN P16 [get_ports io_usb_rx]
set_property PACKAGE_PIN P15 [get_ports io_usb_tx]
set_property IOSTANDARD LVCMOS33 [get_ports io_usb_rx]
set_property IOSTANDARD LVCMOS33 [get_ports io_usb_tx]

# FT2232H Interface
set_property PACKAGE_PIN B13 [get_ports io_ft_clk]
set_property IOSTANDARD LVCMOS33 [get_ports io_ft_clk]

set_property PACKAGE_PIN F5 [get_ports io_ft_rxf]
set_property PACKAGE_PIN B15 [get_ports io_ft_txe]
set_property IOSTANDARD LVCMOS33 [get_ports io_ft_rxf]
set_property IOSTANDARD LVCMOS33 [get_ports io_ft_txe]

set_property PACKAGE_PIN E13 [get_ports io_ft_rd]
set_property PACKAGE_PIN F15 [get_ports io_ft_wr]
set_property PACKAGE_PIN D15 [get_ports io_ft_oe]
set_property IOSTANDARD LVCMOS33 [get_ports io_ft_rd]
set_property IOSTANDARD LVCMOS33 [get_ports io_ft_wr]
set_property IOSTANDARD LVCMOS33 [get_ports io_ft_oe]

# FT Data pins (bidirectional in real design, simplified here)
set_property PACKAGE_PIN A13 [get_ports {io_ft_data_in[0]}]
set_property PACKAGE_PIN A10 [get_ports {io_ft_data_in[1]}]
set_property PACKAGE_PIN B12 [get_ports {io_ft_data_in[2]}]
set_property PACKAGE_PIN B10 [get_ports {io_ft_data_in[3]}]
set_property PACKAGE_PIN C13 [get_ports {io_ft_data_in[4]}]
set_property PACKAGE_PIN C11 [get_ports {io_ft_data_in[5]}]
set_property PACKAGE_PIN D13 [get_ports {io_ft_data_in[6]}]
set_property PACKAGE_PIN D11 [get_ports {io_ft_data_in[7]}]
set_property PACKAGE_PIN E12 [get_ports {io_ft_data_in[8]}]
set_property PACKAGE_PIN E11 [get_ports {io_ft_data_in[9]}]
set_property PACKAGE_PIN F13 [get_ports {io_ft_data_in[10]}]
set_property PACKAGE_PIN F12 [get_ports {io_ft_data_in[11]}]
set_property PACKAGE_PIN G13 [get_ports {io_ft_data_in[12]}]
set_property PACKAGE_PIN G11 [get_ports {io_ft_data_in[13]}]
set_property PACKAGE_PIN H11 [get_ports {io_ft_data_in[14]}]
set_property PACKAGE_PIN H12 [get_ports {io_ft_data_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_ft_data_in[*]}]

set_property PACKAGE_PIN A13 [get_ports {io_ft_data_out[0]}]
set_property PACKAGE_PIN A10 [get_ports {io_ft_data_out[1]}]
set_property PACKAGE_PIN B12 [get_ports {io_ft_data_out[2]}]
set_property PACKAGE_PIN B10 [get_ports {io_ft_data_out[3]}]
set_property PACKAGE_PIN C13 [get_ports {io_ft_data_out[4]}]
set_property PACKAGE_PIN C11 [get_ports {io_ft_data_out[5]}]
set_property PACKAGE_PIN D13 [get_ports {io_ft_data_out[6]}]
set_property PACKAGE_PIN D11 [get_ports {io_ft_data_out[7]}]
set_property PACKAGE_PIN E12 [get_ports {io_ft_data_out[8]}]
set_property PACKAGE_PIN E11 [get_ports {io_ft_data_out[9]}]
set_property PACKAGE_PIN F13 [get_ports {io_ft_data_out[10]}]
set_property PACKAGE_PIN F12 [get_ports {io_ft_data_out[11]}]
set_property PACKAGE_PIN G13 [get_ports {io_ft_data_out[12]}]
set_property PACKAGE_PIN G11 [get_ports {io_ft_data_out[13]}]
set_property PACKAGE_PIN H11 [get_ports {io_ft_data_out[14]}]
set_property PACKAGE_PIN H12 [get_ports {io_ft_data_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_ft_data_out[*]}]

set_property PACKAGE_PIN F14 [get_ports {io_ft_be_out[0]}]
set_property PACKAGE_PIN G14 [get_ports {io_ft_be_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_ft_be_out[*]}]

# Saleae Debug outputs
set_property PACKAGE_PIN B28 [get_ports {io_saleae[0]}]
set_property PACKAGE_PIN A28 [get_ports {io_saleae[1]}]
set_property PACKAGE_PIN A30 [get_ports {io_saleae[2]}]
set_property PACKAGE_PIN A31 [get_ports {io_saleae[3]}]
set_property PACKAGE_PIN A25 [get_ports {io_saleae[4]}]
set_property PACKAGE_PIN A26 [get_ports {io_saleae[5]}]
set_property PACKAGE_PIN B27 [get_ports {io_saleae[6]}]
set_property PACKAGE_PIN B25 [get_ports {io_saleae[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_saleae[*]}]

# Address Bus (20 bits)
set_property PACKAGE_PIN C49 [get_ports {io_addr[19]}]
set_property PACKAGE_PIN C6 [get_ports {io_addr[18]}]
set_property PACKAGE_PIN C5 [get_ports {io_addr[17]}]
set_property PACKAGE_PIN C3 [get_ports {io_addr[16]}]
set_property PACKAGE_PIN C28 [get_ports {io_addr[15]}]
set_property PACKAGE_PIN C30 [get_ports {io_addr[14]}]
set_property PACKAGE_PIN C31 [get_ports {io_addr[13]}]
set_property PACKAGE_PIN B6 [get_ports {io_addr[12]}]
set_property PACKAGE_PIN B5 [get_ports {io_addr[11]}]
set_property PACKAGE_PIN B3 [get_ports {io_addr[10]}]
set_property PACKAGE_PIN B2 [get_ports {io_addr[9]}]
set_property PACKAGE_PIN B48 [get_ports {io_addr[8]}]
set_property PACKAGE_PIN B49 [get_ports {io_addr[7]}]
set_property PACKAGE_PIN A33 [get_ports {io_addr[6]}]
set_property PACKAGE_PIN A34 [get_ports {io_addr[5]}]
set_property PACKAGE_PIN C33 [get_ports {io_addr[4]}]
set_property PACKAGE_PIN C34 [get_ports {io_addr[3]}]
set_property PACKAGE_PIN C36 [get_ports {io_addr[2]}]
set_property PACKAGE_PIN C37 [get_ports {io_addr[1]}]
set_property PACKAGE_PIN C39 [get_ports {io_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_addr[*]}]

# Data Bus (8 bits)
set_property PACKAGE_PIN C40 [get_ports {io_data[0]}]
set_property PACKAGE_PIN C42 [get_ports {io_data[1]}]
set_property PACKAGE_PIN C43 [get_ports {io_data[2]}]
set_property PACKAGE_PIN A24 [get_ports {io_data[3]}]
set_property PACKAGE_PIN A23 [get_ports {io_data[4]}]
set_property PACKAGE_PIN A15 [get_ports {io_data[5]}]
set_property PACKAGE_PIN A14 [get_ports {io_data[6]}]
set_property PACKAGE_PIN A12 [get_ports {io_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_data[*]}]

# Control Signals
set_property PACKAGE_PIN C46 [get_ports io_conn_rw]
set_property PACKAGE_PIN C48 [get_ports io_conn_oe]
set_property PACKAGE_PIN C2 [get_ports io_conn_ci]
set_property PACKAGE_PIN A6 [get_ports io_conn_e2]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_rw]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_oe]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_ci]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_e2]

# Memory Bank Signals
set_property PACKAGE_PIN A11 [get_ports io_conn_mskrom]
set_property PACKAGE_PIN A9 [get_ports io_conn_sram1]
set_property PACKAGE_PIN A8 [get_ports io_conn_sram2]
set_property PACKAGE_PIN C45 [get_ports io_conn_eprom]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_mskrom]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_sram1]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_sram2]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_eprom]

# Power Signals
set_property PACKAGE_PIN D9 [get_ports io_conn_stnby]
set_property PACKAGE_PIN D8 [get_ports io_conn_vbatt]
set_property PACKAGE_PIN C27 [get_ports io_conn_vpp]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_stnby]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_vbatt]
set_property IOSTANDARD LVCMOS33 [get_ports io_conn_vpp]

# Pull-ups on all input pins to prevent floating
set_property PULLUP TRUE [get_ports {io_addr[*]}]
set_property PULLUP TRUE [get_ports {io_data[*]}]
set_property PULLUP TRUE [get_ports io_conn_rw]
set_property PULLUP TRUE [get_ports io_conn_oe]
set_property PULLUP TRUE [get_ports io_conn_ci]
set_property PULLUP TRUE [get_ports io_conn_e2]
set_property PULLUP TRUE [get_ports io_conn_mskrom]
set_property PULLUP TRUE [get_ports io_conn_sram1]
set_property PULLUP TRUE [get_ports io_conn_sram2]
set_property PULLUP TRUE [get_ports io_conn_eprom]
set_property PULLUP TRUE [get_ports io_conn_stnby]
set_property PULLUP TRUE [get_ports io_conn_vbatt]
set_property PULLUP TRUE [get_ports io_conn_vpp]