#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from e500_ft import (
    FT_STREAM_VERSION,
    TICK_NS,
    FtKind,
    FtRecord,
    config_delay_ticks,
    config_enabled,
    iter_timed_records,
    overflow_count,
    read_ft_records,
    sync_version,
    validate_ft_records,
)


@dataclass(frozen=True)
class Signal:
    ident: str
    width: int
    name: str


class VcdWriter:
    def __init__(self, timescale: str = "1ns") -> None:
        self.timescale = timescale
        self._signals: dict[str, Signal] = {}
        self._next_id = 33
        self._started = False
        self._last_time = -1
        self._lines: list[str] = []

    def add_signal(self, name: str, width: int = 1) -> Signal:
        if name in self._signals:
            raise ValueError(f"duplicate VCD signal {name!r}")
        ident = chr(self._next_id)
        self._next_id += 1
        signal = Signal(ident=ident, width=width, name=name)
        self._signals[name] = signal
        return signal

    def header(self) -> None:
        if self._started:
            return
        self._started = True
        self._lines.extend(
            [
                "$date",
                "  generated by ft_to_vcd.py",
                "$end",
                "$version",
                "  e500 ft decoder",
                "$end",
                f"$timescale {self.timescale} $end",
                "$scope module e500_ft $end",
            ]
        )
        for signal in self._signals.values():
            self._lines.append(f"$var wire {signal.width} {signal.ident} {signal.name} $end")
        self._lines.extend(["$upscope $end", "$enddefinitions $end"])

    def change(self, time_ns: int, signal_name: str, value: int) -> None:
        if not self._started:
            self.header()
        signal = self._signals[signal_name]
        if time_ns < self._last_time:
            raise ValueError("VCD time must be monotonic")
        if time_ns != self._last_time:
            self._lines.append(f"#{time_ns}")
            self._last_time = time_ns
        if signal.width == 1:
            self._lines.append(f"{1 if value else 0}{signal.ident}")
        else:
            self._lines.append(f"b{value:0{signal.width}b} {signal.ident}")

    def text(self) -> str:
        if not self._started:
            self.header()
        return "\n".join(self._lines) + "\n"


def build_vcd(records: Iterable[FtRecord]) -> str:
    records = validate_ft_records(records)
    writer = VcdWriter(timescale="1ns")
    for name, width in (
        ("meta_ft_enabled", 1),
        ("meta_stream_version", 8),
        ("meta_kind", 8),
        ("meta_delta_ticks", 32),
        ("meta_classify_delay_ticks", 18),
        ("meta_overflow_count", 26),
        ("bus_addr", 18),
        ("bus_data", 8),
        ("bus_rw", 1),
        ("bus_oe", 1),
        ("bus_ce1", 1),
        ("bus_ce6", 1),
        ("bus_same_addr", 1),
        ("bus_same_data", 1),
        ("bus_classified_after_delay", 1),
        ("event_access", 1),
        ("event_ce1_read", 1),
        ("event_ce1_write", 1),
        ("event_ce6_read", 1),
        ("event_ce6_write_attempt", 1),
        ("event_sync", 1),
        ("event_config", 1),
        ("event_overflow", 1),
    ):
        writer.add_signal(name, width)
    writer.header()

    # Initial values so waveform viewers don't start in X state.
    for signal, width in (
        ("meta_ft_enabled", 1),
        ("meta_stream_version", 8),
        ("meta_kind", 8),
        ("meta_delta_ticks", 32),
        ("meta_classify_delay_ticks", 18),
        ("meta_overflow_count", 26),
        ("bus_addr", 18),
        ("bus_data", 8),
        ("bus_rw", 1),
        ("bus_oe", 1),
        ("bus_ce1", 1),
        ("bus_ce6", 1),
        ("bus_same_addr", 1),
        ("bus_same_data", 1),
        ("bus_classified_after_delay", 1),
        ("event_access", 1),
        ("event_ce1_read", 1),
        ("event_ce1_write", 1),
        ("event_ce6_read", 1),
        ("event_ce6_write_attempt", 1),
        ("event_sync", 1),
        ("event_config", 1),
        ("event_overflow", 1),
    ):
        writer.change(0, signal, 0)

    for timed in iter_timed_records(records):
        time_ns = timed.tick * TICK_NS
        record = timed.record
        writer.change(time_ns, "meta_kind", int(record.kind))
        writer.change(time_ns, "meta_delta_ticks", record.delta_ticks)
        writer.change(time_ns, "bus_addr", record.addr)
        writer.change(time_ns, "bus_data", record.data)
        writer.change(time_ns, "bus_rw", int(record.aux.rw))
        writer.change(time_ns, "bus_oe", int(record.aux.oe))
        writer.change(time_ns, "bus_ce1", int(record.aux.ce1))
        writer.change(time_ns, "bus_ce6", int(record.aux.ce6))
        writer.change(time_ns, "bus_same_addr", int(record.aux.same_addr))
        writer.change(time_ns, "bus_same_data", int(record.aux.same_data))
        writer.change(time_ns, "bus_classified_after_delay", int(record.aux.classified_after_delay))

        pulse_names = [
            "event_access",
            "event_ce1_read",
            "event_ce1_write",
            "event_ce6_read",
            "event_ce6_write_attempt",
            "event_sync",
            "event_config",
            "event_overflow",
        ]
        for pulse in pulse_names:
            writer.change(time_ns, pulse, 0)

        if record.kind == FtKind.SYNC:
            writer.change(time_ns, "meta_stream_version", sync_version(record))
            writer.change(time_ns, "event_sync", 1)
            writer.change(time_ns + TICK_NS, "event_sync", 0)
        elif record.kind == FtKind.CONFIG:
            writer.change(time_ns, "meta_classify_delay_ticks", config_delay_ticks(record))
            writer.change(time_ns, "meta_ft_enabled", int(config_enabled(record)))
            writer.change(time_ns, "event_config", 1)
            writer.change(time_ns + TICK_NS, "event_config", 0)
        elif record.kind == FtKind.OVERFLOW:
            writer.change(time_ns, "meta_overflow_count", overflow_count(record))
            writer.change(time_ns, "event_overflow", 1)
            writer.change(time_ns + TICK_NS, "event_overflow", 0)
        else:
            writer.change(time_ns, "event_access", 1)
            if record.kind == FtKind.CE1_READ:
                writer.change(time_ns, "event_ce1_read", 1)
            elif record.kind == FtKind.CE1_WRITE:
                writer.change(time_ns, "event_ce1_write", 1)
            elif record.kind == FtKind.CE6_READ:
                writer.change(time_ns, "event_ce6_read", 1)
            elif record.kind == FtKind.CE6_WRITE_ATTEMPT:
                writer.change(time_ns, "event_ce6_write_attempt", 1)

            writer.change(time_ns + TICK_NS, "event_access", 0)
            writer.change(time_ns + TICK_NS, "event_ce1_read", 0)
            writer.change(time_ns + TICK_NS, "event_ce1_write", 0)
            writer.change(time_ns + TICK_NS, "event_ce6_read", 0)
            writer.change(time_ns + TICK_NS, "event_ce6_write_attempt", 0)

    return writer.text()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert PC-E500 FT records to VCD")
    parser.add_argument("input", type=Path, help="raw FT capture file of 16-bit little-endian words")
    parser.add_argument("-o", "--output", type=Path, required=True, help="output VCD path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    records = read_ft_records(args.input)
    vcd = build_vcd(records)
    args.output.write_text(vcd)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
