#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
from __future__ import annotations

import argparse
from dataclasses import dataclass
from itertools import groupby
from pathlib import Path
from typing import Iterable, TextIO

from e500_ft import (
    TICK_NS,
    FtKind,
    FtRecord,
    config_delay_ticks,
    config_enabled,
    iter_ft_records_from_path,
    iter_validated_ft_records,
    iter_timed_records,
    overflow_count,
    sync_version,
    validate_ft_records,
)


@dataclass(frozen=True)
class Signal:
    ident: str
    width: int
    name: str


class VcdWriter:
    def __init__(self, timescale: str = "1ns", out: TextIO | None = None) -> None:
        self.timescale = timescale
        self._signals: dict[str, Signal] = {}
        self._next_id = 33
        self._started = False
        self._last_time = -1
        self._out = out
        self._lines: list[str] | None = [] if out is None else None

    def _emit(self, line: str) -> None:
        if self._out is not None:
            self._out.write(line)
            self._out.write("\n")
        else:
            assert self._lines is not None
            self._lines.append(line)

    def add_signal(self, name: str, width: int = 1) -> Signal:
        if name in self._signals:
            raise ValueError(f"duplicate VCD signal {name!r}")
        ident = chr(self._next_id)
        self._next_id += 1
        signal = Signal(ident=ident, width=width, name=name)
        self._signals[name] = signal
        return signal

    def header(self) -> None:
        if self._started:
            return
        self._started = True
        for line in (
            "$date",
            "  generated by ft_to_vcd.py",
            "$end",
            "$version",
            "  e500 ft decoder",
            "$end",
            f"$timescale {self.timescale} $end",
            "$scope module e500_ft $end",
        ):
            self._emit(line)
        for signal in self._signals.values():
            self._emit(f"$var wire {signal.width} {signal.ident} {signal.name} $end")
        self._emit("$upscope $end")
        self._emit("$enddefinitions $end")

    def change(self, time_ns: int, signal_name: str, value: int) -> None:
        if not self._started:
            self.header()
        signal = self._signals[signal_name]
        if time_ns < self._last_time:
            raise ValueError("VCD time must be monotonic")
        if time_ns != self._last_time:
            self._emit(f"#{time_ns}")
            self._last_time = time_ns
        if signal.width == 1:
            self._emit(f"{1 if value else 0}{signal.ident}")
        else:
            self._emit(f"b{value:0{signal.width}b} {signal.ident}")

    def text(self) -> str:
        if not self._started:
            self.header()
        assert self._lines is not None
        return "\n".join(self._lines) + "\n"


PULSE_NAMES = (
    "event_bus_change",
    "event_idle_change",
    "event_ce1_read",
    "event_ce1_write",
    "event_ce6_read",
    "event_ce6_write_attempt",
    "event_sync",
    "event_config",
    "event_overflow",
)


def _group_records_by_time(records: Iterable[FtRecord]) -> Iterable[tuple[int, list[FtRecord]]]:
    for tick, group in groupby(iter_timed_records(records), key=lambda timed: timed.tick):
        yield tick * TICK_NS, [timed.record for timed in group]


def _write_record_group(time_ns: int, records: list[FtRecord], writer: VcdWriter) -> list[str]:
    active_pulses = {name: 0 for name in PULSE_NAMES}

    for record in records:
        writer.change(time_ns, "meta_kind", int(record.kind))
        writer.change(time_ns, "meta_delta_ticks", record.delta_ticks)
        writer.change(time_ns, "bus_addr", record.addr)
        writer.change(time_ns, "bus_data", record.data)
        writer.change(time_ns, "bus_rw", int(record.aux.rw))
        writer.change(time_ns, "bus_oe", int(record.aux.oe))
        writer.change(time_ns, "bus_ce1", int(record.aux.ce1))
        writer.change(time_ns, "bus_ce6", int(record.aux.ce6))
        writer.change(time_ns, "bus_same_addr", int(record.aux.same_addr))
        writer.change(time_ns, "bus_same_data", int(record.aux.same_data))
        writer.change(time_ns, "bus_change_record", int(record.aux.change_record))

        if record.kind == FtKind.SYNC:
            writer.change(time_ns, "meta_stream_version", sync_version(record))
            active_pulses["event_sync"] = 1
        elif record.kind == FtKind.CONFIG:
            writer.change(time_ns, "meta_classify_delay_ticks", config_delay_ticks(record))
            writer.change(time_ns, "meta_ft_enabled", int(config_enabled(record)))
            active_pulses["event_config"] = 1
        elif record.kind == FtKind.OVERFLOW:
            writer.change(time_ns, "meta_overflow_count", overflow_count(record))
            active_pulses["event_overflow"] = 1
        else:
            active_pulses["event_bus_change"] = 1
            if record.kind == FtKind.BUS_CHANGE:
                active_pulses["event_idle_change"] = 1
            elif record.kind == FtKind.CE1_READ:
                active_pulses["event_ce1_read"] = 1
            elif record.kind == FtKind.CE1_WRITE:
                active_pulses["event_ce1_write"] = 1
            elif record.kind == FtKind.CE6_READ:
                active_pulses["event_ce6_read"] = 1
            elif record.kind == FtKind.CE6_WRITE_ATTEMPT:
                active_pulses["event_ce6_write_attempt"] = 1

    for pulse in PULSE_NAMES:
        writer.change(time_ns, pulse, active_pulses[pulse])

    return [pulse for pulse, active in active_pulses.items() if active]


def _write_vcd_records(records: Iterable[FtRecord], writer: VcdWriter) -> None:
    for name, width in (
        ("meta_ft_enabled", 1),
        ("meta_stream_version", 8),
        ("meta_kind", 8),
        ("meta_delta_ticks", 32),
        ("meta_classify_delay_ticks", 18),
        ("meta_overflow_count", 26),
        ("bus_addr", 18),
        ("bus_data", 8),
        ("bus_rw", 1),
        ("bus_oe", 1),
        ("bus_ce1", 1),
        ("bus_ce6", 1),
        ("bus_same_addr", 1),
        ("bus_same_data", 1),
        ("bus_change_record", 1),
        *[(name, 1) for name in PULSE_NAMES],
    ):
        writer.add_signal(name, width)
    writer.header()

    # Initial values so waveform viewers don't start in X state.
    for signal, width in (
        ("meta_ft_enabled", 1),
        ("meta_stream_version", 8),
        ("meta_kind", 8),
        ("meta_delta_ticks", 32),
        ("meta_classify_delay_ticks", 18),
        ("meta_overflow_count", 26),
        ("bus_addr", 18),
        ("bus_data", 8),
        ("bus_rw", 1),
        ("bus_oe", 1),
        ("bus_ce1", 1),
        ("bus_ce6", 1),
        ("bus_same_addr", 1),
        ("bus_same_data", 1),
        ("bus_change_record", 1),
        *[(name, 1) for name in PULSE_NAMES],
    ):
        writer.change(0, signal, 0)

    active_pulses: list[str] = []
    last_time_ns: int | None = None
    for time_ns, record_group in _group_records_by_time(records):
        for pulse in active_pulses:
            writer.change(time_ns, pulse, 0)
        active_pulses = _write_record_group(time_ns, record_group, writer)
        last_time_ns = time_ns

    if last_time_ns is not None:
        for pulse in active_pulses:
            writer.change(last_time_ns + TICK_NS, pulse, 0)


def build_vcd(records: Iterable[FtRecord]) -> str:
    writer = VcdWriter(timescale="1ns")
    _write_vcd_records(validate_ft_records(records), writer)
    return writer.text()


def write_vcd(records: Iterable[FtRecord], out: TextIO) -> None:
    writer = VcdWriter(timescale="1ns", out=out)
    _write_vcd_records(iter_validated_ft_records(records), writer)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert PC-E500 FT records to VCD")
    parser.add_argument("input", type=Path, help="raw FT capture file of 16-bit little-endian words")
    parser.add_argument("-o", "--output", type=Path, required=True, help="output VCD path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    with args.output.open("w") as handle:
        write_vcd(iter_ft_records_from_path(args.input), handle)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
