# Auto-generated from ACF constraints:
# - ../spade-projects/test-minimal-spade/constraints/alchitry_minimal.acf
# - ../../shared-constraints/saleae.acf

set_property PACKAGE_PIN N14 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN P6 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]
set_property PACKAGE_PIN K13 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K12 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN L14 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN L13 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN M16 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN M14 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN M12 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN N16 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN P15 [get_ports {usb_rx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_rx}]
set_property PACKAGE_PIN P16 [get_ports {usb_tx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_tx}]
set_property PACKAGE_PIN M15 [get_ports {saleae[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[0]}]
set_property PACKAGE_PIN P14 [get_ports {saleae[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[1]}]
set_property PACKAGE_PIN E1 [get_ports {saleae[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[2]}]
set_property PACKAGE_PIN F2 [get_ports {saleae[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[3]}]
set_property PACKAGE_PIN F4 [get_ports {saleae[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[4]}]
set_property PACKAGE_PIN F3 [get_ports {saleae[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[5]}]
set_property PACKAGE_PIN C4 [get_ports {saleae[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[6]}]
set_property PACKAGE_PIN D4 [get_ports {saleae[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[7]}]

create_clock -name clk -period 10.000 [get_ports {clk}]

# Vivado placement override for Au clock pin mapping
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]

# Allow bitstream generation even when some ports are intentionally left unconstrained
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
