name = "sharp_pc_g850_streaming_rom_spade"

[libraries]
shared_components = { path = "../shared-components" }

[verilog]
sources = ["../shared-verilog/clk_wiz_0.v"]

[tooling]
top = "main"
test_module = "test_sharp_pc_g850_streaming_rom"

[simulation]
testbench_dir = "test"
