name = "pin_tester_spade"
preprocessing = ["python3 ../tools/gen_build_info.py --project ."]

[libraries]
shared_components = { path = "../shared-components" }

[constraints]
auto = true

[tooling]
top = "main"
test_module = "test_pin_tester"

[simulation]
testbench_dir = "test"
