name = "sharp_organizer_card_spade"

[libraries]
shared_components = { path = "../shared-components" }

[constraints]
auto = true

[verilog]
sources = ["../shared-verilog/clk_wiz_0.v"]

[tooling]
top = "main"
test_module = "test_sharp_organizer_card"

[simulation]
testbench_dir = "test"
