# Auto-generated from ACF constraints:
# - ../../Alchitry-Labs-V2/src/main/resources/library/components/Constraints/alchitry.acf
# - ../../../shared-constraints/saleae.acf
#   meta.schema: 1
#   meta.name: saleae_debug_header
#   meta.board: alchitry_au1
#   meta.description: Saleae D0-D7 mapping used by retrobus Spade projects; use minimum drive and FAST slew to help capture more 100MHz clock pulses on Logic MSO digital probes.
#   meta.root_property.saleae.DRIVE: 4
#   meta.root_property.saleae.SLEW: FAST
# - constraints/pc-e500-ffc.acf
#   meta.schema: 1
#   meta.name: sharp_pc_e500_card_ffc
#   meta.board: alchitry_au1
#   meta.description: Sharp PC-E500 card signal mapping. Physical FPGA pin assignments intentionally match the proven pin-tester wiring.

set_property PACKAGE_PIN N14 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN P6 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]
set_property PACKAGE_PIN K13 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K12 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN L14 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN L13 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN M16 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN M14 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN M12 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN N16 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN P15 [get_ports {usb_rx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_rx}]
set_property PACKAGE_PIN P16 [get_ports {usb_tx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_tx}]
set_property PACKAGE_PIN M15 [get_ports {saleae[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[0]}]
set_property PACKAGE_PIN P14 [get_ports {saleae[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[1]}]
set_property PACKAGE_PIN E1 [get_ports {saleae[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[2]}]
set_property PACKAGE_PIN F2 [get_ports {saleae[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[3]}]
set_property PACKAGE_PIN F4 [get_ports {saleae[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[4]}]
set_property PACKAGE_PIN F3 [get_ports {saleae[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[5]}]
set_property PACKAGE_PIN C4 [get_ports {saleae[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[6]}]
set_property PACKAGE_PIN D4 [get_ports {saleae[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[7]}]
set_property PACKAGE_PIN R6 [get_ports {rw}]
set_property IOSTANDARD LVCMOS33 [get_ports {rw}]
set_property PACKAGE_PIN R7 [get_ports {addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[0]}]
set_property PACKAGE_PIN T8 [get_ports {addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[1]}]
set_property PACKAGE_PIN T5 [get_ports {addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[2]}]
set_property PACKAGE_PIN R5 [get_ports {addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[3]}]
set_property PACKAGE_PIN T13 [get_ports {addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[4]}]
set_property PACKAGE_PIN T12 [get_ports {addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[5]}]
set_property PACKAGE_PIN R12 [get_ports {addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[6]}]
set_property PACKAGE_PIN P11 [get_ports {addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[7]}]
set_property PACKAGE_PIN N12 [get_ports {addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[8]}]
set_property PACKAGE_PIN N11 [get_ports {addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[9]}]
set_property PACKAGE_PIN R8 [get_ports {addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[10]}]
set_property PACKAGE_PIN L2 [get_ports {addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[11]}]
set_property PACKAGE_PIN L3 [get_ports {addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[12]}]
set_property PACKAGE_PIN J1 [get_ports {addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[13]}]
set_property PACKAGE_PIN K5 [get_ports {addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[14]}]
set_property PACKAGE_PIN E6 [get_ports {addr[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[15]}]
set_property PACKAGE_PIN P13 [get_ports {addr[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[16]}]
set_property PACKAGE_PIN M1 [get_ports {addr[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[17]}]
set_property PACKAGE_PIN M2 [get_ports {vcc2}]
set_property IOSTANDARD LVCMOS33 [get_ports {vcc2}]
set_property PACKAGE_PIN P1 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property PACKAGE_PIN R1 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property PACKAGE_PIN R2 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property PACKAGE_PIN J3 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property PACKAGE_PIN B1 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property PACKAGE_PIN C1 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property PACKAGE_PIN E2 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property PACKAGE_PIN A2 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property PACKAGE_PIN B2 [get_ports {ce1}]
set_property IOSTANDARD LVCMOS33 [get_ports {ce1}]
set_property PACKAGE_PIN R3 [get_ports {ce6}]
set_property IOSTANDARD LVCMOS33 [get_ports {ce6}]
set_property PACKAGE_PIN T3 [get_ports {nc}]
set_property IOSTANDARD LVCMOS33 [get_ports {nc}]
set_property PULLDOWN true [get_ports {nc}]
set_property PACKAGE_PIN T4 [get_ports {oe}]
set_property IOSTANDARD LVCMOS33 [get_ports {oe}]

set_property DRIVE 4 [get_ports {saleae[0]}]
set_property SLEW FAST [get_ports {saleae[0]}]
set_property DRIVE 4 [get_ports {saleae[1]}]
set_property SLEW FAST [get_ports {saleae[1]}]
set_property DRIVE 4 [get_ports {saleae[2]}]
set_property SLEW FAST [get_ports {saleae[2]}]
set_property DRIVE 4 [get_ports {saleae[3]}]
set_property SLEW FAST [get_ports {saleae[3]}]
set_property DRIVE 4 [get_ports {saleae[4]}]
set_property SLEW FAST [get_ports {saleae[4]}]
set_property DRIVE 4 [get_ports {saleae[5]}]
set_property SLEW FAST [get_ports {saleae[5]}]
set_property DRIVE 4 [get_ports {saleae[6]}]
set_property SLEW FAST [get_ports {saleae[6]}]
set_property DRIVE 4 [get_ports {saleae[7]}]
set_property SLEW FAST [get_ports {saleae[7]}]

create_clock -name clk -period 10.000 [get_ports {clk}]
create_clock -name cycle_start -period 1310.000 [get_ports {nc}]

# Vivado placement override for Au clock pin mapping
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {nc_IBUF}]

# Allow bitstream generation even when some ports are intentionally left unconstrained
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
