name = "shared_components"

[libraries]
protocols.git = "https://gitlab.com/spade-lang/lib/protocols"
ready_valid.git = "https://gitlab.com/spade-lang/lib/ready_valid"

[tooling]
top = "tb_sync2"
test_module = "test_sync2"

[verilog]
sources = ["verilog/**/*.v"]

[simulation]
testbench_dir = "test"
