name: 'Setup Chisel Environment'
description: 'Install and configure Java, SBT, and Python for Chisel + FuseSOC development'
inputs:
  java-version:
    description: 'Java version to install'
    required: false
    default: '17'
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'
  install-fusesoc:
    description: 'Whether to install FuseSOC'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
    
    - name: Install SBT
      shell: bash
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt
    
    - name: Set up Python ${{ inputs.python-version }}
      if: inputs.install-fusesoc == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install FuseSOC
      if: inputs.install-fusesoc == 'true'
      shell: bash
      run: |
        pip install fusesoc==2.4.3
        fusesoc --version
    
    - name: Cache SBT dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.cache/coursier
          gateware/chisel/target
          gateware/chisel/project/target
        key: sbt-${{ runner.os }}-${{ hashFiles('gateware/chisel/build.sbt', 'gateware/chisel/project/build.properties') }}
        restore-keys: |
          sbt-${{ runner.os }}-
    
    - name: Cache pip dependencies
      if: inputs.install-fusesoc == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-