# Auto-generated from ACF constraints:
# - ../../Alchitry-Labs-V2/src/main/resources/library/components/Constraints/alchitry.acf
# - ../../../shared-constraints/saleae.acf
#   meta.schema: 1
#   meta.name: saleae_debug_header
#   meta.board: alchitry_au1
#   meta.description: Saleae D0-D7 mapping used by retrobus Spade projects.
#   meta.root_property.saleae.DRIVE: 4
#   meta.root_property.saleae.SLEW: SLOW
# - ../../../pin-tester/constraint/level-shifter.acf

set_property PACKAGE_PIN N14 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN P6 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]
set_property PACKAGE_PIN K13 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K12 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN L14 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN L13 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN M16 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN M14 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN M12 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN N16 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN P15 [get_ports {usb_rx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_rx}]
set_property PACKAGE_PIN P16 [get_ports {usb_tx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_tx}]
set_property PACKAGE_PIN M15 [get_ports {saleae[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[0]}]
set_property PACKAGE_PIN P14 [get_ports {saleae[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[1]}]
set_property PACKAGE_PIN E1 [get_ports {saleae[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[2]}]
set_property PACKAGE_PIN F2 [get_ports {saleae[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[3]}]
set_property PACKAGE_PIN F4 [get_ports {saleae[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[4]}]
set_property PACKAGE_PIN F3 [get_ports {saleae[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[5]}]
set_property PACKAGE_PIN C4 [get_ports {saleae[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[6]}]
set_property PACKAGE_PIN D4 [get_ports {saleae[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saleae[7]}]
set_property PACKAGE_PIN T10 [get_ports {ffc_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[0]}]
set_property PACKAGE_PIN T9 [get_ports {ffc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[1]}]
set_property PACKAGE_PIN R6 [get_ports {ffc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[2]}]
set_property PACKAGE_PIN R7 [get_ports {ffc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[3]}]
set_property PACKAGE_PIN T8 [get_ports {ffc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[4]}]
set_property PACKAGE_PIN T7 [get_ports {ffc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[5]}]
set_property PACKAGE_PIN T5 [get_ports {ffc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[6]}]
set_property PACKAGE_PIN R5 [get_ports {ffc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[7]}]
set_property PACKAGE_PIN T13 [get_ports {ffc_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[8]}]
set_property PACKAGE_PIN R13 [get_ports {ffc_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[9]}]
set_property PACKAGE_PIN T12 [get_ports {ffc_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[10]}]
set_property PACKAGE_PIN R12 [get_ports {ffc_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[11]}]
set_property PACKAGE_PIN P11 [get_ports {ffc_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[12]}]
set_property PACKAGE_PIN P10 [get_ports {ffc_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[13]}]
set_property PACKAGE_PIN N12 [get_ports {ffc_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[14]}]
set_property PACKAGE_PIN N11 [get_ports {ffc_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[15]}]
set_property PACKAGE_PIN R8 [get_ports {ffc_data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[16]}]
set_property PACKAGE_PIN P8 [get_ports {ffc_data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[17]}]
set_property PACKAGE_PIN L2 [get_ports {ffc_data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[18]}]
set_property PACKAGE_PIN L3 [get_ports {ffc_data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[19]}]
set_property PACKAGE_PIN J1 [get_ports {ffc_data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[20]}]
set_property PACKAGE_PIN K1 [get_ports {ffc_data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[21]}]
set_property PACKAGE_PIN K5 [get_ports {ffc_data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[22]}]
set_property PACKAGE_PIN E6 [get_ports {ffc_data[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[23]}]
set_property PACKAGE_PIN P13 [get_ports {ffc_data[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[24]}]
set_property PACKAGE_PIN N13 [get_ports {ffc_data[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[25]}]
set_property PACKAGE_PIN M1 [get_ports {ffc_data[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[26]}]
set_property PACKAGE_PIN M2 [get_ports {ffc_data[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[27]}]
set_property PACKAGE_PIN P1 [get_ports {ffc_data[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[28]}]
set_property PACKAGE_PIN N1 [get_ports {ffc_data[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[29]}]
set_property PACKAGE_PIN R1 [get_ports {ffc_data[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[30]}]
set_property PACKAGE_PIN R2 [get_ports {ffc_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[31]}]
set_property PACKAGE_PIN T2 [get_ports {ffc_data[40]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[40]}]
set_property PACKAGE_PIN R3 [get_ports {ffc_data[41]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[41]}]
set_property PACKAGE_PIN T3 [get_ports {ffc_data[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[42]}]
set_property PACKAGE_PIN T4 [get_ports {ffc_data[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[43]}]
set_property PACKAGE_PIN R16 [get_ports {ffc_data[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[44]}]
set_property PACKAGE_PIN R15 [get_ports {ffc_data[45]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[45]}]
set_property PACKAGE_PIN T15 [get_ports {ffc_data[46]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[46]}]
set_property PACKAGE_PIN T14 [get_ports {ffc_data[47]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[47]}]
set_property PACKAGE_PIN H3 [get_ports {ffc_data[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[32]}]
set_property PACKAGE_PIN J3 [get_ports {ffc_data[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[33]}]
set_property PACKAGE_PIN B1 [get_ports {ffc_data[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[34]}]
set_property PACKAGE_PIN C1 [get_ports {ffc_data[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[35]}]
set_property PACKAGE_PIN D1 [get_ports {ffc_data[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[36]}]
set_property PACKAGE_PIN E2 [get_ports {ffc_data[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[37]}]
set_property PACKAGE_PIN A2 [get_ports {ffc_data[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[38]}]
set_property PACKAGE_PIN B2 [get_ports {ffc_data[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ffc_data[39]}]

set_property DRIVE 4 [get_ports {saleae[0]}]
set_property SLEW SLOW [get_ports {saleae[0]}]
set_property DRIVE 4 [get_ports {saleae[1]}]
set_property SLEW SLOW [get_ports {saleae[1]}]
set_property DRIVE 4 [get_ports {saleae[2]}]
set_property SLEW SLOW [get_ports {saleae[2]}]
set_property DRIVE 4 [get_ports {saleae[3]}]
set_property SLEW SLOW [get_ports {saleae[3]}]
set_property DRIVE 4 [get_ports {saleae[4]}]
set_property SLEW SLOW [get_ports {saleae[4]}]
set_property DRIVE 4 [get_ports {saleae[5]}]
set_property SLEW SLOW [get_ports {saleae[5]}]
set_property DRIVE 4 [get_ports {saleae[6]}]
set_property SLEW SLOW [get_ports {saleae[6]}]
set_property DRIVE 4 [get_ports {saleae[7]}]
set_property SLEW SLOW [get_ports {saleae[7]}]

create_clock -name clk -period 10.000 [get_ports {clk}]

# Vivado placement override for Au clock pin mapping
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]

# Allow bitstream generation even when some ports are intentionally left unconstrained
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
