name = "binary_counter"
preprocessing = ["python3 ../../tools/gen_build_info.py --project ."]

[libraries]
shared_components = { path = "../../lib/shared-components" }

[constraints]
auto = true

[tooling]
top = "main"
test_module = "counter_pins"

[simulation]
testbench_dir = "test"
