name: Alchitry Labs V2 CI

on:
  push:
    branches: [ master, main ]
    paths:
      - 'gateware/**'
      - '.github/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'gateware/**'
      - '.github/**'

jobs:
  check-projects:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project:
          - test-minimal
          - pin-tester
          - sharp-organizer-card
          - sharp-pc-g850-bus
          - sharp-pc-g850-streaming-rom
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Get latest Alchitry Labs version
      id: get-version
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/alchitry/Alchitry-Labs-V2/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
        echo "Latest Alchitry Labs version: ${LATEST_VERSION}"
    
    - name: Cache Alchitry Labs installation
      uses: actions/cache@v4
      with:
        path: |
          ~/alchitry-labs
          ~/.cache/alchitry
        key: alchitry-labs-v2-${{ runner.os }}-${{ steps.get-version.outputs.version }}
        restore-keys: |
          alchitry-labs-v2-${{ runner.os }}-
    
    - name: Install Alchitry Labs V2
      run: |
        export ALCHITRY_VERSION="${{ steps.get-version.outputs.version }}"
        ./.github/install-alchitry-labs.sh
    
    - name: Run project tests using shared script
      run: |
        ./.github/scripts/run-alchitry-tests.sh ${{ matrix.project }}
    
    - name: Upload build artifacts (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs-${{ matrix.project }}
        path: |
          gateware/${{ matrix.project }}/*.log
          gateware/${{ matrix.project }}/build/
        retention-days: 7
        if-no-files-found: ignore

  summary:
    runs-on: ubuntu-latest
    needs: check-projects
    if: always()
    
    steps:
    - name: Check overall status
      run: |
        if [ "${{ needs.check-projects.result }}" == "success" ]; then
          echo "✅ All Alchitry Labs V2 projects passed syntax checks!"
        else
          echo "❌ Some Alchitry Labs V2 projects failed syntax checks"
          exit 1
        fi
