name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: python -m pip install -e .[dev]
    
    - name: Run Ruff
      run: |
        cd py
        ruff check . || (echo "Ruff check failed" && exit 1)

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: python -m pip install -e .[dev]
    
    - name: Run Mypy
      run: ./.github/scripts/run-mypy.sh

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: python -m pip install -e .[dev]
    
    - name: Run tests
      run: |
        cd py
        pytest

  summary:
    if: always()
    runs-on: ubuntu-latest
    name: Test Summary
    needs: [ruff, mypy, test]
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.ruff.result }}" == "failure" || "${{ needs.mypy.result }}" == "failure" || "${{ needs.test.result }}" == "failure" ]]; then
            echo "One or more tests failed"
            exit 1
          else
            echo "All tests passed"
          fi
