name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v1
      with:
        python-version: '3.12'

    - name: Sync dependencies
      run: uv sync --extra dev

    - name: Run Ruff
      run: uv run ruff check . || (echo "Ruff check failed" && exit 1)

  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v1
      with:
        python-version: '3.12'

    - name: Sync dependencies
      run: uv sync --extra dev

    - name: Run Mypy
      run: uv run -- ../.github/scripts/run-mypy.sh

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v1
      with:
        python-version: '3.12'

    - name: Sync dependencies
      run: uv sync --extra dev

    - name: Run tests
      run: uv run pytest

  summary:
    if: always()
    runs-on: ubuntu-latest
    name: Test Summary
    needs: [ruff, mypy, test]
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.ruff.result }}" == "failure" || "${{ needs.mypy.result }}" == "failure" || "${{ needs.test.result }}" == "failure" ]]; then
            echo "One or more tests failed"
            exit 1
          else
            echo "All tests passed"
          fi
