name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    - name: Run Ruff
      run: |
        cd py
        ruff check .

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd py
        pip install -e .
        pip install mypy types-protobuf
    
    - name: Run Mypy
      run: |
        cd py
        mypy --ignore-missing-imports .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd py
        pip install -e .
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        cd py
        pytest --cov=. --cov-report=xml --cov-report=term
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./py/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  summary:
    if: always()
    runs-on: ubuntu-latest
    name: Test Summary
    needs: [ruff, mypy, test]
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.ruff.result }}" == "failure" || "${{ needs.mypy.result }}" == "failure" || "${{ needs.test.result }}" == "failure" ]]; then
            echo "One or more tests failed"
            exit 1
          else
            echo "All tests passed"
          fi